import Head from 'next/head'
import Link from "next/link";
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import { useState } from "react";
import styles from '@/styles/Home.module.css'
import Button from './Button';
import Stepper from './Stepper';

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const [toggle, setToggle] = useState(false)
  // const toggleButton = () =>{
  //   setToggle(!toggle)
  // }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
      <Link href="/about" className="btn-primary">
        Click here to go to the About page
      </Link>
      <Stepper />
      <Button />
    </nav>
    </>
  )
}
